[project]
name = "open-medical-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.19.2",
    "boto3>=1.43.89",
    "cryptography>=50.0.1",
    "fastapi>=0.141.1",
    "groq>=1.7.0",
    "opentelemetry-distro[otlp]>=0.65b0",
    "opentelemetry-instrumentation-fastapi>=0.65b0",
    "opentelemetry-instrumentation-requests>=0.65b0",
    "opentelemetry-instrumentation-sqlalchemy>=0.65b0",
    "pgvector>=0.5.0",
    "psycopg[binary]>=3.3.5",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
    "sqlalchemy>=2.0.52",
    "sse-starlette>=3.0.3",
    "starlette>=0.40.0,<0.47.0",
    "uvicorn>=0.52.4",
]
