[project]
name = "open-medical-worker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.43.89",
    "docling>=2.126.0",
    "langchain-text-splitters>=1.1.2",
    "pgvector>=0.5.0",
    "psycopg[binary]>=3.3.5",
    "pymupdf>=1.28.2",
    "pymupdf4llm>=1.28.2",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
    "sqlalchemy>=2.0.52",
    "tiktoken>=0.14.0",
]